- internal/goofys.go
- internal/goofys_test.go
- internal/handles.go
> return . and .. in readdir

- .travis.yml
- internal/goofys_test.go
- test/fuse-test.sh
fuse-test.sh is mostly from s3fs, with some minor modifications
to make it run in this environment and some tests disabled
> test the fuse layer

- Makefile
Resolves out-of-memory issues with range requests.
> Refresh S3Proxy snapshot

- internal/handles.go
This fixes the issues I saw in #122
> Use SSE(if enabled) when calling MkDir

- Makefile
Release notes:
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.5.0
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.5.1
> Upgrade to S3Proxy 1.5.1

- test/fuse-test.sh
Compared via:
```
diff -wu \
<(sed -e s/describe/echo/ -e s/return/exit/ -e 's/add_tests //' \
~/work/s3fs-fuse/test/integration-test-main.sh) \
test/fuse-test.sh
```
> Sync with s3fs integration tests

- Makefile
Release notes:
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.5.2
> Upgrade to S3Proxy 1.5.2

- README.md
homebrew/fuse has been merged into homebrew core: https://github.com/Homebrew/homebrew-core/pull/11283
> update homebrew instruction

- README.md
> Update readme to avoid accidentally erasing AWS credentials

- Makefile
Changelog:
https://github.com/gaul/s3proxy/releases
> Upgrade to S3Proxy 1.6.0

- internal/dir.go
- internal/handles.go
- test/fuse-test.sh
This allows file names with ASCII values 1-10.
> URL encode ListObject responses

- README.md
> Document Go 1.9 dependency

- README.md
I tested Wasabit and Digital Ocean. They work! With the -endpoint flag.
> adding 2 provdiers I tested

- .travis.yml
- Makefile
- test/run-tests.sh
Current travis settings is too old, so I updated.
> update ci settings: base distribution and java/golang version

- api/api.go
- internal/flags.go
- internal/goofys.go
Closes #292.
Includes a drive-by fix by @msmitherdc (I assume).
r? @msmitherdc.
#292 also has a test for the stat cache, do we want to include it?
> Add support for Requester Pays buckets

- internal/cgroup.go
This fixes getting the cgroup memory limit/usage within a docker container (on newer version of docker)
> Fix docker memory limit

- Makefile
Release notes:
https://github.com/gaul/s3proxy/releases/tag/s3proxy-1.7.0
> Upgrade to S3Proxy 1.7.0

- api/common/logger.go
> use SetLevel() instead of Level = ? to prevent data race

- internal/backend_s3.go
This prevented compilation on arm7 systems like Raspberry Pi. Fixes #724.
> Fix 32-bit constant overflow

- internal/v2signer.go
> Fix timeFormat for x-amz-date, two-digit day of month as per RFC 7231

- api/common/panic_logger.go
Fix build error after updating jacobsa/fuse to v0.0.0-20221016084658-a4cd154343d8 (https://github.com/kahing/goofys/issues/732)
> Fix build error from dependency update
