kahing/goofys

- internal/goofys.go
- internal/goofys_test.go
I've not been able to get the tests to run on my Mac, but I can build and mount with this change.
Closes #28
> Compatibility with aws-sdk-go v0.10.0

- internal/flags.go
- main.go
`$HOME/.aws/credentials` supports multiple profiles via Windows
INI-style stanzas.
> Add support for AWS profiles

- internal/buffer_pool.go
> Use mem.Available including buffers and cache

- main.go
Fix for #84
Restoring default credentials object to "a chain of credential providers to search for credentials in environment variables, shared credential file, and EC2 Instance Roles" 
http://docs.aws.amazon.com/sdk-for-go/api/aws/Config.html#Credentials-field
Previously, the "Credentials" field was left nil if there was no "--profile" argument. Now the Credentials field will be left at the default.
> restoring default credentials object

- README.md
Use 'AWS_ACCESS_KEY_ID' and 'AWS_SECRET_ACCESS_KEY' environment variable names
in README.md. These names match verbatim what the user sees in "Add
user", and correspond with other AWS utility configurations.
https://github.com/aws/aws-sdk-go#configuring-credentials
The underlying aws-sdk-go accepts the shorthand as a fallback, but if
the user has the full length variables set and goes to set the variables
listed in the docs thinking they are what Goofys uses, they will be in
for a suprise as the full length names take precedence. Changing the
docs to the full name- as this commit does- prevents that 'oops.'
> Use full length env variable names.

- internal/buffer_pool_test.go
- internal/goofys.go
- internal/goofys_test.go
- internal/handles.go
- internal/logger.go
- main.go
From https://github.com/sirupsen/logrus#logrus-
> Seeing weird case-sensitive problems? Unfortunately, the author failed to realize the consequences of renaming to lower-case. Due to the Go package environment, this caused issues. Regretfully, there's no turning back now. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.
> Lowercase github.com/Sirupsen/logrus

- .travis.yml
- api/api.go
- internal/goofys.go
I'm currently extending `goofys` to add local caching for some specific use cases in which `catfs` does not serve our needs.  However, the current API of the `goofys/api` package is very limited (as it only allows you to mount).  It would be really useful to be able to create a  `goofys/internal.Goofys` struct such that certain functions of the `github.com/jacobsa/fuse/fuseutil.FileSystem` interface can be overridden; but the associated goofys functions and types are currently walled off in the `goofys/internal` package, which cannot be imported.
This PR exposes a few of the functions and types from the `internal` package that enable extending `goofys`. I also added a `GetFullName` function I've found very useful.  This PR makes no functional changes but would be awesome to have …
> Expose NewGoofys in `github.com/kahing/goofys/api` package

- api/api.go
- internal/flags.go
We use goofys to do random reads in large files stored in S3.  Most of the time, the GetObject requests to S3 are very fast - less than 100 ms.  But occasionally - about 1 in 1000 requests - it takes much longer.  Several seconds, even up to 20 seconds.  The 30 second timeout is nice, but in our case we've found that a much shorter timeout and quick retry works better for us - as low as 1 second really helped even out our response times.
I've added a command line flag `-http-timeout` to set the value, but it has the same default as the previous hard-coded value (30 seconds).  So it should behave exactly the same if you don't specify the flag.
> Add command line option to override http.Client Timeout

- internal/goofys_test.go
Addresses errors of the form:
```
internal/goofys_test.go:120: C.Log call has possible formatting
directive %v
```
> Fix unformatted logging call

- api/api.go
This is needed so the [Docker plugin](https://github.com/djmaze/goofys-docker) can run flawlessly in a Docker swarm cluster.
> Allow static credentials in API

- internal/flags.go
- internal/goofys.go
- internal/perms.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- Makefile
Notably this includes support for List Objects v2.  Release notes:
https://github.com/gaul/s3proxy/releases/tag/s3proxy-1.6.2
> Upgrade to S3Proxy 1.6.2

- internal/backend_azblob.go
- internal/goofys_test.go
`azblob.ListBlobs(fooblob/)` returns `fooblob` which might make goofys think `fooblob` is a prefix and not a blob. This change fixes this behavior.
> azblob.ListBlobs: Don't return foo on ListBlobs for foo/

- README.md
> Add Scaleway to list of compatible non-AWS S3 providers

- go.mod
- go.sum
- internal/dir.go
- internal/file.go
- internal/goofys.go
- internal/goofys_test.go
- internal/handles.go
Currently, Goofys uses a forked version of fuse library that exposed PID to handle FlushFile operation from different processes (discussed in https://github.com/kahing/goofys/issues/273).
Now that the uptream project has implemented this https://github.com/jacobsa/fuse/pull/92, we should move back there and get benefits from upstream changes.
This PR should address multiple issues we have
1. https://github.com/kahing/goofys/issues/676
2. https://github.com/kahing/goofys/issues/682
3. https://github.com/kahing/goofys/issues/674
4. https://github.com/kahing/goofys/issues/663
Tested by running `./test/run-tests.sh`
[test.log](https://github.com/kahing/goofys/files/8553346/test.log)
> switching fuse lib to upstream

- README.md
- internal/file.go
Increase max part size for multipart upload from 125MB to 625MB. As a result, we can write new files up to ~5TB from goofys. Related issue https://github.com/kahing/goofys/issues/686.
Tested manually by writing a file with size more than 1TB and running `make run-test` passed.
> Support writing files larger than 1TB

- api/api.go
- internal/goofys_test.go
This allows identifying mounts as "fuse.goofys" instead of only
"fuse".
> Set subtype to goofys

- internal/backend_s3.go
- internal/flags.go
- main.go
This PR add "goofys/version-hash" to the user agent list for each request. You will be able to identify which requests come from goofys and which version if you enable [server access logging](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html) or [CloudTrail](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudtrail-logging-s3-info.html) on your buckets.
example for debug_s3 log
```
2022/05/18 10:08:32.838728 s3.DEBUG DEBUG: Request s3/ListObjectsV2 Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /<REDACTED>?delimiter=%2F&list-type=2&prefix= HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: goofys/0.24.0-829d8e5ce20faa3f9f6f054077a14325e00e9249 aws-sdk-go/1.38.7 (go1.18.2; linux; amd64)
Accept-Encoding: identity
Authorization: …
```
> Add goofys as user agent for s3 request

- README.md
I've spent a few hours navigating goofy's issues and getting `2021-06-16T17:11:03.392028+00:00 ip-10-10-73-45 kernel: [   9.551179] fuse: Unknown parameter '--file-mode` when following the README instructions to mount on startup.
The suggested package `fuse-utils` was not found on `Ubuntu 20.04.2 LTS` mirros, but installing fuse with `sudo apt install fuse` worked and the bucket is now mounted on startup.
Let me know if you want the message rephrased clarifying the ubuntu version
Thank you for your awesome work maintaining the lib!
> 📚 Add note on the correct package name required to mount on startup

- api/common/panic_logger.go
- internal/cgroup.go
`os.Stat` is never returning `err` which satisfies `os.IsExist(err) == true`
the only way to make sure that file exists using `os.Stat` is to check `err == nil`
```
if _, err := os.Stat("/file/that/exists"); os.IsExist(err) {
// will never trigger!
// why? because os.Stat runs normally if file exists.
// it's expected behaviour for os.Stat, so it doesn't throw an error
// os.IsExist() does not receive an error ( it's nil ), so it can't tell you
// if the error message was "file not found"
}
```
from https://pkg.go.dev/os#File.Stat
```
Stat returns the FileInfo structure describing file. If there is an error, it will be of type *PathError.
```
also I installed go mods from scratch and it required additional method for `FusePanicLogger` to satisfy `fuseutil.FileSystem`
I added the method
> Fix potential memory consumption and OOMs by fixing logic in `getCgroupAvailableMem`

- api/common/panic_logger.go
This PR fixes broken build due to FusePanicLogger.BatchForget duplicate block (#740).
> Fix FusePanicLogger.BatchForget redeclared in this block
